coisa = input('Digite algo: ')
print('O tipo primitivo disso é'.format(type(coisa)))
print('Isso é Alphanumerico ?{}'.format(coisa.isalnum()))
print('Isso é um número ?{}'.format(coisa.isnumeric()))
print('Isso é um decimal ?{}'.format(coisa.isdecimal()))
print('Isso é Alfabético ?{}'.format(coisa.isalpha()))
print('Isso é ASCII ?{}'.format(coisa.isascii()))
print('Isso é um Digito ?{}'.format(coisa.isdigit()))
print('Isso está em maiúsculo? ?{}'.format(coisa.isupper()))
print('Isso está minúsculo? ?{}'.format(coisa.islower()))
print('Isso está Identifier? ?{}'.format(coisa.isidentifier()))
print('Isso é um printtable ?{}'.format(coisa.isprintable()))
print('Isso é um espaço ?{}'.format(coisa.isspace()))
print('Isso está Capitalizado ?{}'.format(coisa.istitle()))