num = int(input('Digite um número: '))
print('='*20)
print('O dobro de {} é {}.'.format(num, (num*2)))
print('O Triplo de {} é {}.'.format(num, (num*3)))
print('A raiz de {} é {:.2f}.'.format(num, (num ** (1/2))))
print('='*20)